project:
  type: website
  
website:
  title: "COFFEE 2"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: sources.qmd
        text: Sources
      - href: Data Analys.qmd
        text: Data Analys

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



